### ISSUE TITLE
Ertekeles

### ISSUE THREAD

**Issue by hegyhati** [Uni-Sopron/termelesiranyitas-o22-jobshopstaff#1]
@kakasnest  kerlek itt irj, ha van valami, hogy ne kelljen kodot keresgetni, stb.

Amiket e-mailben irtal, azt nem teljesen ertem, de a kododat megneztem. Az "alapabb" modellnek nagyon sok ertelme nincs, igazabol lerakja a precedencia szbaalyoknak megfeleloen oket valahogy.

A parhuzamos gepes dolog mar erdekesebb, jonak is tunik, bar job-shophoz sok koze nincs. 

A plotolashoz talan szebb volna, ha csak egy json-t generalna ki a modell, amit megenne a python kod. 

Illetve jo lett volna nem csak egy eleg pici adathalmazzal kiprobalni, hanem generalni hozza sok bemenetet, es megnezni, hogy szuperal.

Jegyen meg gondolkodom, 4 fele hajlok.

**Comment by hegyhati** [comment]
Legyen 5, de csinald meg kerlek a plotolos dolgot.

**Comment by kakasnest** [comment]
Rendben, ma még mindenképp foglalkozom vele!

**Comment by kakasnest** [comment]
Javítottam az output-on, ahogy kérted és a python script pedig ezt dolgozza fel. Nem tudom időd mennyire engedi majd hogy ránézz, de még mindig ugyanaz a problémám, mint volt. Ha kettő gép van, akkor a kiosztást úgy oldja meg, hogy egy gép dolgozik egy időben két feladaton (első és harmadik feladatnál).
![image](https://user-images.githubusercontent.com/60859390/207180182-f0c38783-a420-49d4-a764-38fae91e3236.png)

**Comment by hegyhati** [comment]
Na, a plotolas eleve nem jo olyan szemszogbol, hogy az y tengelyen a gepeknek kellene lenni, es a dobozokba kellene a taszk nevet beleirni. A modellezesi dolog rendben van, valami a plotolasnal megy felre, mert a T2 van az M0-hoz rendelve, a T3 meg az M1-hez. (jsonben is). A baj ha jol latom az, hogy a `color_list`-et adod meg, de ott ketto van, es azt felvaltva hasznalod. Ez akkor lett volna jo, ha nem igy definialod:

```python
color_list = [colors_for_machines[i] for i in colors_for_machines]
````
Ennek konkretan nem sok ertelme van. A kulcsok a `colors_for_machines`-ben az M1, M2. Es akkor beleteszed egy listaba az ezekhez tartozo color ertekeket. 2 db lesz, ezek mennek felvaltva.  Ami Neked jo lett volna:

```python
color_list = [ colors_for_machines[task['machine']] for task in data['tasks'] ]
```
vagy valami ilyesmi, es akkor annyi szin lett volna, amennyi taszk van a listaban. Mert most azon a ketton megy korbe-korbe. De amugy elotte csomot szenvedtel azzal, hogy belefuzted a task-okba a szineket, szoval:
```python
color_list  = [ task['color'] for task in data['tasks'] ]
```
Nomeg persze tok felesleges egy object, amiben van egyetlen kulcs. 

De igazabol mivel eleve a machine-ok vannak az y tengelyen, ezert az egesz plotolast at kell irni.

**Comment by kakasnest** [comment]
Bökte a csőröm, hogy nem fejeztem be ezt a feladatot rendesen, így most utólag igyekeztem áttekinteni és javítani az egészet. Biztos lehetne még 100x szebben, de azt hiszem, hogy legalább most már nyugodtan fekszem le aludni. 😄

A korábbi gondolatodnál nem értettem, hogy miért szeretnéd, hogy a gépek legyenek az Y tengelyen, lehet nekem más a logikám nagyon, de nálam valahogy zsigerből így jött.
![image](https://user-images.githubusercontent.com/60859390/219153301-a9f6e63f-35c7-439f-b198-dc1f1e3a2506.png)

**Comment by oliverosz** [comment]
Ez a grafikon azt ábrázolja, hogy 30+ gép van, amiből az első 7 dolgozik a T1 taskon, a következő 10 gép a T2-n, a következő 9 gép a T3-on, de abból néhány gép dolgozik a T6-on és a T7-en is. Az pedig nem derül ki, hogy ebből mi mikor történik. Legalábbis a tengelyfeliratok alapján ez van az ábrán.

**Comment by kakasnest** [comment]
Alulra véletlenül nem időt írtam, hoppá-hoppá...😅 Javítottam! 😃

**Comment by hegyhati** [comment]
@kakasnest  azert jobb, ha a Machine-ok vannak az y tengelyen, mert akkor azonnal latszik, hogy osztottam-e be ket feladatot ugyanabban az idoben ugyanarra a gepre. Itt most azt kell nezegetnem, hogy vannak-e olyan teglalapok, amiknek ugyanaz a szine, es egymas fole lognak. 

Emellett minden sorba igy csak 1 dobozod kerul, ami vizualis pazarlas erosen. Tipikusan joval kesebb gep van, mint feladat. Kepzeld el, hogy mi lenne 10 machine es 40 feladat eseten. De ha forditva lenne, akkor meg kepzelj el ahogy 40 szin kozott probalnad keresni az egyezo szinueket. 

Szoval na, nem veletlenul olyan a Gantt amilyen ;-)

**Comment by kakasnest** [comment]
Átírtam úgy, hogy most a taskok data label-ök és a gépek vannak az Y-on. Ez így tényleg egy kompaktabb nézet! 😄 

![image](https://user-images.githubusercontent.com/60859390/219973765-ed662214-6f8f-435a-8828-175bdd65bf78.png)

**Comment by hegyhati** [comment]
Na, akkor mar csak az utolso cseszegetes: Nem az egy gepen levoknek kell ugyanazt a szint adni, mert az nem hordoz semmilyen informaciot. Hanem az egy job-hoz tartozo taszkok kapjak ugyanazt a szint :-)

**Comment by kakasnest** [comment]
Igyekeztem beletenni ezt a Taskok Jobhoz rendelése logikát, viszont lehet nem a legjobb megoldással oldottam meg. 😅  

Ilyen lett végül. 😄
![image](https://user-images.githubusercontent.com/60859390/221019671-0027f0a5-f79e-41fe-8506-465f72a40d74.png)

**Comment by oliverosz** [comment]
Alakul... Annyi, hogy a klasszikus job-shop ütemezésnél csak jobon belül vannak precedencia-relációk. Most minden job első taszkjának be kell fejeződnie, hogy bármelyik job 2. taszkja elkezdődhessen. T8-nak csak a T4-re kéne épülnie, és akkor korábban elkezdődhetne, más jobtól nem kéne függenie.

A fentiek miatt általában úgy indexeljük a taszkokat, hogy [job,stage], és ez egyben megadja a precedenciákat is, de a te modelleden is csak egy kicsit kell változtatni, hogy úgy működjön.

**Comment by kakasnest** [comment]
Köszönöm az észrevételt, abszolút jogos! Én észre sem vettem sajnos, ameddig rá nem mutattál. 😅

Igyekeztem kijavítani, elsőre meg is ijedtem, mert azt hittem, hogy még mindig fenn áll a probléma, de kifelejtettem, hogy nem minden gép tud mindent csinálni, a többit azért viszont szépen tömbösítette. 😄 
![image](https://user-images.githubusercontent.com/60859390/221668629-ac8813fc-3f48-4610-b067-9ce9ce2cd2c3.png)

Amit viszont nem tudok, hogy most tuti jó-e. Lehet a modellen kellene még valamit változtatnom (lehet, hogy sok mindent is), mivel test adatoknál, ha pl. bennhagyom, hogy nincs külön-külön gép, hanem minden tud mindent, akkor annyi változóval dolgozik, hogy szerintem egy nap alatt sem számolja ki. (Az előbb kb. 5 perc után lőttem ki, hiába volt LP megoldás szinte rögtön, mivel MILP-re viszont még akkor sem.) Erre esetleg ötlet?

**Comment by oliverosz** [comment]
> Amit viszont nem tudok, hogy most tuti jó-e.
Hát igen, a bizonyítás nehezebb. De ha felrakod a modell új változatát is, akkor rá tudunk nézni, hátha látunk benne hibát.

A hosszú megoldási időre meg a GLPK megoldójának a hibája. Ez nem nehéz feladatokra, hanem oktatási célokra való. Open-source megoldóból is van komolyabb (pl.: [Cbc](https://github.com/coin-or/Cbc)), a kereskedelmi szoftverek meg még jobbak, pl. a Gurobi vagy a CPLEX.

**Comment by kakasnest** [comment]
Áh, értem, azt hittem valamit szimplán rosszul közelítek meg, ezért ilyen a teljesítmény. Igen, pár példát Máté is említett, talán pont ugyanezeket. Most rákukkantottam, hátha van utóbbiaknak ingyenes változata, de azt hiszem nem véletlenül kereskedelmi.

Hálásan köszönöm az észrevételeket és megyjegyzéseket mindkettőtöknek! Így azért sokkal pofásabb lett. 😄 (Szóljatok, ha zárjam az Issue-t, ameddig van változtatni való, addig nem akarom idő előtt zárni, nem célom a menekülés. 😃 )

**Comment by oliverosz** [comment]
A Gurobinál van könnyen aktiválható academic license. CPLEX-et jó ideje nem használtam, de elvileg ott is van, de emlékeim szerint elég körülményes az igénylése.

**Comment by hegyhati** [comment]
Reszemrol close-olhato :-)
Jah, es orulok, hogy kipofoztad, igy azert kerekebb :-)

**Comment by kakasnest** [comment]
Én is örülök és köszönöm, hogy támogattátok a folytatást! 😄
